# Generated by Django 3.1.2 on 2020-10-14 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=30)),
                ('vorname', models.CharField(max_length=30)),
                ('plz', models.IntegerField()),
                ('wohnort', models.CharField(max_length=50)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.IntegerField()),
                ('addresszusatz', models.CharField(max_length=100)),
                ('telefonnummer', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('geburtstag', models.DateField()),
                ('registrierungs_zeit', models.DateTimeField(default=datetime.datetime(2020, 10, 14, 13, 30, 57, 875703, tzinfo=utc))),
                ('geschlecht', models.CharField(max_length=10)),
                ('titel', models.CharField(max_length=20)),
            ],
        ),
    ]
