# Generated by Django 3.1.2 on 2020-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='registrierungs_zeit',
            field=models.DateTimeField(),
        ),
    ]
