# Generated by Django 3.1.2 on 2020-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20201019_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodenprobe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunden_id', models.IntegerField()),
                ('mail_text', models.TextField()),
                ('eingangsdatum', models.DateTimeField()),
                ('pdf_erstellungsdatum', models.DateField()),
                ('raw_data_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='kunde',
            name='addresszusatz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='geburtstag',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='hausnummer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='plz',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='strasse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='telefonnummer',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='titel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='wohnort',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
