# Generated by Django 3.1.2 on 2020-10-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_auto_20201019_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='raw_filename',
            field=models.CharField(default='*.*', max_length=35),
        ),
    ]
