# Generated by Django 3.1.2 on 2020-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_bodenprobe_raw_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='anrede',
            field=models.CharField(default='Frau/Herr', max_length=20),
        ),
    ]
