# Generated by Django 3.1.2 on 2020-10-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_kunde_anrede'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='current_state',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
