# Generated by Django 3.1.2 on 2020-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20201020_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='payment_received',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
