# Generated by Django 3.1.2 on 2020-10-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_bodenprobe_payment_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='custom_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='price',
            field=models.FloatField(default=19.95),
        ),
        migrations.AlterField(
            model_name='bodenprobe',
            name='current_state',
            field=models.IntegerField(default=0),
        ),
    ]
