# Generated by Django 3.1.2 on 2020-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20201021_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='land',
            field=models.CharField(default='Deutschland', max_length=40),
        ),
        migrations.AlterField(
            model_name='bodenprobe',
            name='raw_filename',
            field=models.CharField(default='*', max_length=35),
        ),
    ]
