# Generated by Django 3.1.2 on 2020-10-29 19:29

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20201028_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kunden_id', models.IntegerField()),
                ('anzahl_bodenproben', models.IntegerField(default=1)),
                ('notizen', models.TextField(blank=True)),
                ('preis', models.FloatField(default=19.5)),
                ('nachlass', models.FloatField(default=0)),
                ('bereits_gezahlt', models.BooleanField(default=False)),
                ('label_name', models.CharField(blank=True, max_length=50)),
                ('mail_auftrags_text', models.TextField(blank=True)),
                ('status', models.CharField(default='Neuer Auftrag', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='bodenprobe',
            old_name='kunden_id',
            new_name='auftrags_id',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='custom_name',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='payment_received',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='raw_data_path',
        ),
        migrations.RemoveField(
            model_name='bodenprobe',
            name='raw_filename',
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='label_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='pdf_auswertung_kunde',
            field=models.FileField(default='*', upload_to=workflow.models.getFilename),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='pdf_original',
            field=models.FileField(default='*', upload_to=workflow.models.getFilename),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='status',
            field=models.CharField(default='Auftrag gerade erst reingekommen', max_length=50),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='xlsx_auswertung',
            field=models.FileField(default='*', upload_to=workflow.models.getFilename),
        ),
        migrations.AddField(
            model_name='kunde',
            name='update_emails',
            field=models.BooleanField(default=False),
        ),
    ]
