# Generated by Django 3.1.2 on 2020-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_auto_20201029_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='geburtstag',
            field=models.DateField(blank=True, null=True),
        ),
    ]
