# Generated by Django 3.1.2 on 2020-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_auto_20201029_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='auftrag',
            name='eingangs_zeit',
            field=models.DateTimeField(null=True),
        ),
    ]
