# Generated by Django 3.1.2 on 2020-11-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auftrag_eingangs_zeit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kunde',
            old_name='addresszusatz',
            new_name='adresszusatz',
        ),
        migrations.AlterField(
            model_name='kunde',
            name='nachname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kunde',
            name='vorname',
            field=models.CharField(max_length=50),
        ),
    ]
