# Generated by Django 3.1.2 on 2020-11-01 15:30

from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_auto_20201101_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodenprobe',
            name='pdf_auswertung_kunde',
            field=models.FileField(blank=True, default='*', upload_to=workflow.models.getFilename),
        ),
        migrations.AlterField(
            model_name='bodenprobe',
            name='pdf_original',
            field=models.FileField(blank=True, default='*', upload_to=workflow.models.getFilename),
        ),
        migrations.AlterField(
            model_name='bodenprobe',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bodenprobe',
            name='xlsx_auswertung',
            field=models.FileField(blank=True, default='*', upload_to=workflow.models.getFilename),
        ),
    ]
