# Generated by Django 3.1.2 on 2020-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_auto_20201101_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='raw_data_path',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='raw_filename',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
