# Generated by Django 3.1.2 on 2020-11-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20201111_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunde',
            name='hausnummer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
