# Generated by Django 3.1.2 on 2020-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_auto_20201126_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpmValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=2)),
                ('value', models.FloatField()),
                ('bodenprobe_id', models.IntegerField()),
            ],
        ),
    ]
