# Generated by Django 3.1.2 on 2020-12-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20201201_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='auftrag',
            name='ergebnisse_zurueckgemeldet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='preis',
            field=models.FloatField(default=18),
        ),
    ]
