# Generated by Django 3.1.2 on 2020-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0022_auto_20201203_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='ergebnisse_zurueckgemeldet',
            field=models.IntegerField(default=0),
        ),
    ]
