# Generated by Django 3.1.2 on 2021-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_auto_20201203_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(default='Deutschland', max_length=40)),
                ('address_suffix', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='alt_sampling_point_address_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='is_billing_address_sampling_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auftrag',
            name='preis',
            field=models.FloatField(default=15),
        ),
    ]
