# Generated by Django 3.1.2 on 2022-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_auto_20220110_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bodenprobe',
            name='geo_coordinate_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
