# Generated by Django 3.1.2 on 2022-03-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20220115_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodenprobe',
            name='from_duisburg_south',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
